sodenn/lexical-beautiful-mentions

.changeset/wet-boats-leave.md, apps/docs/app/Menu.tsx, packages/lexical-beautiful-mentions/src/BeautifulMentionsPlugin.tsx, packages/lexical-beautiful-mentions/src/BeautifulMentionsPluginProps.ts
=> feat(): add label to BeautifulMentionsMenuItemProps

.changeset/breezy-teachers-destroy.md, README.md, apps/docs/app/Editor.tsx, apps/docs/app/MentionsToolbarPlugin.tsx, apps/docs/tests/menu.spec.ts, packages/lexical-beautiful-mentions/src/BeautifulMentionsPlugin.tsx, packages/lexical-beautiful-mentions/src/BeautifulMentionsPluginProps.ts, packages/lexical-beautiful-mentions/src/ComboboxPlugin.tsx, packages/lexical-beautiful-mentions/src/MentionNode.spec.ts, packages/lexical-beautiful-mentions/src/MentionNode.tsx, packages/lexical-beautiful-mentions/src/Menu.tsx, packages/lexical-beautiful-mentions/src/TypeaheadMenuPlugin.tsx, packages/lexical-beautiful-mentions/src/mention-utils.ts, packages/lexical-beautiful-mentions/src/useMentionLookupService.ts
=> feat(): add additional metadata to mentions

.changeset/orange-buckets-greet.md, plugin/src/useBeautifulMentions.ts
=> feat(): add 'data' field to getMentions function

.changeset/dull-pears-rush.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/BeautifulMentionsPluginProps.ts
=> feat(): add option to enable/disable that the current mentions are displayed as suggestions

.changeset/metal-pants-exist.md, plugin/src/BeautifulMentionsPlugin.tsx
=> feat(): drop check for slash

.changeset/eighty-birds-joke.md, README.md, plugin/src/BeautifulMentionsPluginProps.ts
=> feat(BeautifulMentionComponentProps): data prop with generic type

.changeset/strange-plants-roll.md, package-lock.json, plugin/src/Menu.tsx, www/tests/menu.spec.ts, www/tests/test-utils.ts
=> fix(Menu): remove typeahead element from DOM after menu is closed

.changeset/clean-mirrors-yawn.md, README.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/BeautifulMentionsPluginProps.ts, plugin/src/ComboboxPlugin.tsx, plugin/src/Menu.tsx, plugin/src/useMentionLookupService.ts, www/components/ConfigurationProvider.tsx, www/components/Editor.tsx, www/components/Menu.tsx
=> feat(Menu): add callback fired when the user selects a menu item

.changeset/tough-dots-rest.md, plugin/src/createMentionNode.ts
=> fix(createBeautifulMentionNode): prevent re-creating the BeautifulMentionNode class on every call

.changeset/warm-hats-pretend.md, plugin/src/MentionNode.tsx, plugin/src/ZeroWidthNode.ts, www/components/CustomMentionComponent.tsx
=> fix(BeautifulMentionNode + ZeroWidthNode): fix HTML/JSON node serialization & deserialization

.changeset/flat-drinks-destroy.md, plugin/src/ComboboxPlugin.tsx, plugin/src/Menu.tsx
=> fix(Menu): prevent other key enter commands from blocking the menu from closing

.changeset/lucky-frogs-judge.md, plugin/src/MentionComponent.tsx
=> fix(): onBlur behavior in MentionComponent

.changeset/dirty-trainers-cheer.md, plugin/src/createMentionNode.ts, www/lib/editor-config.ts
=> fix(createBeautifulMentionNode): add missing return type for custom mention node

README.md, www/components/Menu.tsx
=> docs(): update code example

.changeset/happy-jokes-visit.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/mention-commands.ts
=> feat(useBeautifulMentions): allow to insert mentions with data

README.md
=> chore(): update README.md

.changeset/red-squids-lay.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/ZeroWidthPlugin.tsx, plugin/src/mention-commands.ts, www/lib/editor-theme.ts, www/tests/commands.spec.ts
=> fix(): allow to select the text when it ends with a mention

package-lock.json, plugin/package.json
=> chore(): support for react 17 and above

.changeset/olive-papayas-talk.md, plugin/src/MentionComponent.tsx
=> fix(BeautifulMentionComponent): don't reset the editor selection when a blur event occurs #410

.changeset/olive-buses-fetch.md, plugin/src/BeautifulMentionsPlugin.tsx
=> fix(): undo not working after insert mention on focus lost

.changeset/cold-mice-attend.md, plugin/src/MentionComponent.tsx
=> fix(): mention selection not being cleared when clicking outside the editor and focus the editor again

.changeset/new-ravens-visit.md, README.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/BeautifulMentionsPluginProps.ts, plugin/src/mention-utils.ts, www/tests/mention.spec.ts
=> feat(): allow to define a set of characters that can appear directly before the trigger character

README.md
See https://lexical.dev/docs/getting-started/react#creating-basic-rich-text-editor for the correct prop name
=> Fix the prop name in the docs

.changeset/lazy-pots-bow.md, plugin/src/BeautifulMentionsPlugin.tsx, plugin/src/createMentionNode.ts, plugin/src/mention-commands.ts, plugin/src/mention-utils.ts, plugin/src/useBeautifulMentions.ts, www/tests/mention.spec.ts
=> fix(useBeautifulMentions): fix broken functions for custom mention node (removeMentions/renameMentions)

.changeset/cyan-windows-glow.md, plugin/src/mention-utils.ts
=> fix($findBeautifulMentionNodes): add null check for CustomBeautifulMentionNode

.changeset/breezy-deers-begin.md, plugin/src/BeautifulMentionsPlugin.tsx, www/tests/menu.spec.ts
=> feat(): show suggestions even if the cursor is in the middle of the query

.changeset/sixty-jobs-perform.md, plugin/src/BeautifulMentionsPlugin.tsx, www/tests/space.spec.ts
=> fix(): ensure space is added after multi-character trigger mention

.changeset/cold-moons-cry.md, plugin/src/BeautifulMentionsPlugin.tsx, www/tests/mention.spec.ts
=> fix(): prevent unintended deletion of text after inserting a mention

.changeset/fair-seahorses-wave.md, plugin/src/BeautifulMentionsPlugin.tsx, www/tests/menu.spec.ts, www/tests/test-utils.ts
=> fix(mentions): avoid opening the mention menu if no matching results are found

.changeset/spotty-suns-bathe.md, plugin/src/BeautifulMentionsPlugin.tsx, www/tests/mention.spec.ts
=> fix(): insert mentions via keyboard only by enter key

www/playwright.config.ts
Safari tests are flaky in the CI environment
=> test(playwright): skip Safari tests in CI
